// https://github.com/Haivision/srt/blob/master/srtcore/handshake.h

/// The handshake payload (Control Information Field) carried bt SRT control packets.
/// This maps directly onto the wire format defiend in the SRT spec (Handshake CIF).
///
/// Total serialized size is 48 bytes excluding extensions.
/// 4 byte fields + 16 byte peer IP.
#[derive(Debug, PartialEq, Clone)]
pub struct Handshake {
    /// Handshake version.
    /// 4 = legacy / UDT compatible induction request
    /// 5 - SRT (HSv5), used from the conclusion phase onward once both peers
    /// are confirmed to speak SRT
    pub version: u32,

    /// Advertised cipher family / key length for encryption
    /// 0 = no encryption advertised
    /// encryption is not supported yet, therefore this field must always be 0
    pub encryption_field: u16,

    /// Message specific extension flag tied to `handshake_type`
    /// - During INDUCTION, the caller sends 2 (SRT magic will be echoed
    ///   back by the listener) and the listener echoes a value back.
    /// - During CONCLUSION, this is a bitmask of extension types
    ///   (HSREQ / KMREQ / etc.) appended after this payload.
    /// - MUST be 0 in all other cases.
    pub extension_field: u16,

    /// The starting point to track missing packets
    /// The first sequence number will be randomly generated by the sender
    /// Only 31 bits can be used so the top bit is reserved and must be 0 on the wire
    ///
    /// The randomly generated sequence number must be masked with `& 0x7FFF_FFFF`
    /// to ensure this
    pub initial_sequence_number: u32,

    /// The maximum transmission unit (MTU) in bytes
    pub max_transmission_unit: u32,

    /// The amount of packets that can be in flight before the sender must wait
    /// for an acknowledgement from the receiver
    ///
    /// Common defaults to 8192
    pub max_flow_window_size: u32,

    /// Whcih phase of the handshake this packet represents
    /// (Induction / Conclusion / etc). See `HandshakeType` for details.
    pub handshake_type: HandshakeType,

    /// The socket ID the sender wants the peer to use as the destination ID
    /// when routing packets back to the sender.
    pub srt_socket_id: u32,

    /// Anti-Spoofing cookie. 0 in the caller's initial INDUCTION request
    /// The listener generates and returns a cookie derived from the caller's
    /// host, port and time, which the caller should echo back in the CONCLUSION
    /// request to prove it's not a spoofed request.
    pub syn_cookie: u32,

    /// The peer's IP address
    /// Always stored as 16 bytes on the wire
    /// IPv6 natively, or an IPv4 address mapped into the low 4 bytes
    /// with the rest zeroed (this is NOT the standard `::ffff:` IPv4-mapped
    /// form used elsewhere; SRT just zero-pads the unused bytes).
    pub peer_ip: [u8; 16],
}

/// The handshake type / phase, sent as raw u32 on the wire.
///
/// Reference implementation (`UDTRequestType` in handshake.h) uses signed
/// `int32_t` values (e.g. `URQ_CONCLUSION = -1`), which are bit-identical
/// to unsigned discriminants (`-1i32 as u32 == 0xFFFFFFFF`).
/// u32 is used here because that's how the field is documented in the RFC.
#[repr(u32)]
#[derive(Debug, PartialEq, Clone)]
pub enum HandshakeType {
    /// Final step acknowledging the connection is fully established.
    /// (== URQ_DONE / -3 in the reference implementation)
    Done = 0xFFFFFFFD,

    /// Sent by the listener to accept a rendezvous handshake.
    /// (== URQ_AGREEMENT / -2)
    Agreement = 0xFFFFFFFE,

    /// Second phase of the handshake — sender and receiver agree on
    /// final connection parameters and (optionally) exchange extensions.
    /// (== URQ_CONCLUSION / -1)
    Conclusion = 0xFFFFFFFF,

    /// Used only in rendezvous (peer-to-peer) mode, not caller/listener.
    /// (== URQ_WAVEAHAND / 0)
    Waveahand = 0x00000000,

    /// First phase — caller asks the listener for a SYN cookie before
    /// any resources are allocated (mitigates handshake-flood DoS).
    /// (== URQ_INDUCTION / 1)
    Induction = 0x00000001,

    /// Any value we don't recognize. We keep the raw value around so we
    /// can still round-trip it (log it, echo it back, etc.) instead of
    /// silently discarding data we don't understand
    Unknown(u32),
}

impl From<u32> for HandshakeType {
    fn from(value: u32) -> Self {
        match value {
            0xFFFFFFFD => HandshakeType::Done,
            0xFFFFFFFE => HandshakeType::Agreement,
            0xFFFFFFFF => HandshakeType::Conclusion,
            0x00000000 => HandshakeType::Waveahand,
            0x00000001 => HandshakeType::Induction,
            _ => HandshakeType::Unknown(value),
        }
    }
}

impl From<HandshakeType> for u32 {
    fn from(value: HandshakeType) -> Self {
        match value {
            HandshakeType::Done => 0xFFFFFFFD,
            HandshakeType::Agreement => 0xFFFFFFFE,
            HandshakeType::Conclusion => 0xFFFFFFFF,
            HandshakeType::Waveahand => 0x00000000,
            HandshakeType::Induction => 0x00000001,
            HandshakeType::Unknown(value) => value,
        }
    }
}
